---
# tasks file for docker-registry.

- name: Log into DockerHub
  docker_login:
    username: medlahsoumi
    password: f2e1d0a5-9447-4bd5-918c-b4dcbd72ea6c

- name: Tag and push to docker hub
  docker_image:
    name: devops:latest
    repository: medlah2/devops
    tag: end 
    push: yes
