---
# tasks file for docker-registry.

- name: Log into DockerHub
  docker_login:
    username: medlah2
    password: fa4c5cca-de07-4736-9894-fd96a5337a3e

- name: Tag and push to docker hub
  docker_image:
    name: devops:latest
    repository: medlah2/devops
    tag: end 
    push: yes
